### ISSUE TITLE
[BUG] jest-expo prevents Node from reading global.gc correctly

### ISSUE THREAD

**Issue by thymikee** [callstack/reassure#175]
Investigate what's up there in the jest-expo preset that prevents `global.gc` from being correctly populated by the `--expose-gc` flag. See: https://github.com/callstack/reassure/issues/174

**Comment by mcavaliere** [comment]
Worthy of note: I am able to reproduce this error by simply adding `jest-expo` as a dependency and running `yarn reassure`; I don't need to `require()` in my jest.config.js and set it as a preset.

**Comment by mdjastrzebski** [comment]
Resolved by #386. Support for `jest-expo` added in Reassure 0.9.0, which I've released yesterday.
