### ISSUE TITLE
[BUG] native-expo example project not working properly

### ISSUE THREAD

**Issue by challme28** [callstack/reassure#189]
**Describe the bug**
After cloning the repo, `yarn reassure` yields a validation error

```
● Validation Error:

  Module @testing-library/jest-native/extend-expect in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/proximity/IdeaProjects/reassure/examples/native-expo

  Configuration Documentation:
  https://jestjs.io/docs/configuration


❌  Something went wrong, current performance file (.reassure/current.perf) does not exist

✨  Done in 0.98s.
```

**To Reproduce**
1. Clone repo
2. Open `native-expo` project
3. Run `yarn`
4. Run `yarn reassure`

**Expected behavior**
The test run successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/9601561/192396700-13faa139-31c8-4651-b958-097d18d7e892.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook Pro 2019
 - OS: macOS 12.4

**Comment by mdjastrzebski** [comment]
@challme28 this should be fixed now, just update to the current `main`.

The reason why this occurred is that `setupFilesAfterEnv` used `@testing-library/jest-native/extend-expect` while not declaring a dev dependency on `@testing-library/jest-native`. This however would work if you would run `yarn install` in the top level direction, as `examples/native-base` would resolve it from higher level.

**Comment by challme28** [comment]
I went to `/examples` and ran `yarn`. Then it worked.
