### ISSUE TITLE
[FEATURE] Validate performance results files input to compare package

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#208]
**Is your feature request related to a problem? Please describe.**

Currently reading of performance file by `compare` package does not perform any validation, so the CLI could crash with cryptic errors if file is corrupted. 

**Describe the solution you'd like**
Use `zod` or other hight quality library to parse/validate contents of the results file. This will require defining schemas for header and entry rows and should be configured to work with TypeScript. In case of error the information about the incorrect line should be displayed.

**Describe alternatives you've considered**
Write validation by hand, but that would be too not worth the tradeoff of additional deps

**Additional context**
N/A

**Comment by ShaswatPrabhat** [comment]
@mdjastrzebski  I can give this a shot if still open.

**Comment by mdjastrzebski** [comment]
@ShaswatPrabhat go ahead 👍

**Comment by ShaswatPrabhat** [comment]
@mdjastrzebski Please find the [PR](https://github.com/callstack/reassure/pull/216)

Please let me know if this is along the lines of what you had wanted.

Thanks!

**Comment by mdjastrzebski** [comment]
@ShaswatPrabhat thanks for submitting the PRs. Unfortunately I'll need to pause a couple of days on my open source work as I've got cold-like symptoms. I'll review the PRs as soon as I get better.

**Comment by ShaswatPrabhat** [comment]
@mdjastrzebski please take care. Hope you get well soon.

**Comment by ShaswatPrabhat** [comment]
Hi, are there any other maintainers in @mdjastrzebski 's absence who can please help review or merge the given commits.
I was looking for this PR to add to my hacktoberfest credits.

Thanks in advance.

**Comment by mdjastrzebski** [comment]
@ShaswatPrabhat I am back and will check your PR today. Thank you for both contribution and panience 🙂

Re other contributors: we also got @thymikee but he is usually even more busy than I am.
