### ISSUE TITLE
[FEATURE] Reassure init CLI command

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#222]
**Is your feature request related to a problem? Please describe.**
Add `init` command to CLI. This comment would be invoked like this:
```ssh
$ yarn reassure init
```

This command would apply common Reassure setup steps that need to be done by hand now:
- create `reassure-tests.sh` script from [template](https://github.com/callstack/reassure#write-performance-testing-script)
- create dangerfile from [template](https://github.com/callstack/reassure/blob/main/dangerfile.ts)
- add `.reassure` folder to `.gitignore` if present
- show link how to add reassure to CI: https://github.com/callstack/reassure#ci-integration

**Describe the solution you'd like**
Before doing the changes mentioned above tool should check if `reassure-tests.sh` exists, and assume that if it exists then the folder hand been already initialized for Reassure

For subsequent steps (danger file, gitignore): they should be only carried if danger file does not yet exist, or if gitignore does not contain reassure entry.

The tool should be user friendly and have clear help messages.

**Comment by ShaswatPrabhat** [comment]
I can give this a shot in parallel with custom GH Action @mdjastrzebski

**Comment by Xiltyn** [comment]
Seems like there wasn't any PR raised for this one, therefore I'm picking this one up.

**Comment by Xiltyn** [comment]
We'll be merged in https://github.com/callstack/reassure/pull/275
