### ISSUE TITLE
[FEATURE] Ability to measure code execution time

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#224]
**Is your feature request related to a problem? Please describe.**
Reassure can be though as general performance execution measurement and comparison tool. The current `measurePerformance` works on JSX element by rendering it with `React.Profiler`, which is run a number of times and saved to performance file. Next it is compared with baseline performance file using statistical tools.

All of the above steps, except rendering using `React.Profiler` are just working on render durations (& counts), and might as well serve to analyse non-render-related measurements.

**Describe the solution you'd like**
Add `measureDuration` function accepting a callback function with code to measure.
```ts
function measureDuration(callback: () => void, options) 
```

Function body would be similar to existing `measurePerformance`, but would swap rendering code for just running the callback.

User could optionally call following methods inside his code:
```
function timerStart(name):
function timerEnd(name):
```
Calling `timerStart(name)` would capture current timestamp, for given name, using [performance.now()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) if available or `Date.now` otherwise
Calling `timerEnd(name)` would also capture the current timestamp for given name, but would additionally take end and start timestamp calculate their difference, and treat this as `name` event duration.

Having a test without using `timerStart/timerEnd` would add a single line to performance results file. The line would be in the same format as current performance entries. The `name` field would be take from Jest test name, as currently is for render tests. The `durations`-related fields would contain code execution duration, while `count` related fields would assume that count is `1`.

If `timerStart/End` would be used then, each `name` entry should generate additional line:
* `name` of that test would be Jest test name concatenated with timer name: `{testName} - {timerName}`
* `durations` fields would contain sum of given timer durations from given test run
* `count` fields would contain number of how many timers given timer has been run in the same test.

**Comment by sketchomania** [comment]
can a beginner like me work one this ?

**Comment by mdjastrzebski** [comment]
@sketchomania I think you could give it a try. We've picked hacktoberfest tasks to be relatively easy to do.

**Comment by sketchomania** [comment]
do I need to create a sperate folder "measure-duration" for this issue?

**Comment by zacharyfmarion** [comment]
Wanted to leave my 2 cents here - my company wanted to use this for more general metrics as well - for example measure FCP in puppeteer. We created a function similar to measurePerformance that looks like this:

```ts
type Metric = {
  name: string;
  value: number;
};

type MeasureOptions = {
  runs?: number;
  dropWorst?: number;
  scenario: () => Promise<any>;
  getMetrics: () => Promise<Metric[]>;
  onIterationStart?: () => Promise<any>;
  onIterationComplete?: () => Promise<any>;
  page: Page;
};

function measurePerformance(options: MeasureOptions): Promise<MeasureRenderResult[]>
```

You can then use it like this (example from a puppeteer test)

```ts
it('loads the page', async () => {
    async function getMetrics() {
      const metrics = await page.metrics();

      const [{ startTime: firstPaint }] = JSON.parse(
        await page.evaluate(() => JSON.stringify(performance.getEntriesByName('first-paint'))),
      );

      const [{ startTime: firstContentfulPaint }] = JSON.parse(
        await page.evaluate(() =>
          JSON.stringify(performance.getEntriesByName('first-contentful-paint')),
        ),
      );

      return [
        {
          name: 'Script Execution time',
          value: metrics.ScriptDuration as number,
        },
        {
          name: 'First Paint',
          value: firstPaint as number,
        },
        {
          name: 'First Contentful Paint (FCP)',
          value: firstContentfulPaint as number,
        },
      ];
    }

    async function scenario() {
      await page.reload({ waitUntil: 'networkidle2' });
    }

    async function onIterationComplete() {
      const client = await page.target().createCDPSession();
      await client.send('HeapProfiler.enable');
      await client.send('HeapProfiler.collectGarbage');
    }

    await measurePerformance({ scenario, getMetrics, onIterationComplete });
  });
```

This allows you to save multiple metrics at once, and should (I think) be sufficient for re-implementing the current measurePerformance (for example call gc onIterationComplete). Would be nice if we made this API as general as possible.

**Comment by mdjastrzebski** [comment]
@zacharyfmarion thanks for sharing you use case. 

I like `onIterationStart` & `onInterationComplete` however I wonder if there would be any difference between having them as separate functions vs calling them at the beginning and end of `scenario`?

Could you explain the idea behind `getMetric()`? It seems like your `measurePerformance` function does not actually measure anything by itself but rather reads so perf info from the [Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance).
