### ISSUE TITLE
[FEATURE] Setup Docusaurus docs

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#227]
**Is your feature request related to a problem? Please describe.**
Currently we do not have documentation page, but only README. As the amount of documentation grows it would make sense to have it better organized into separate Getting started, API, guides, etc.

**Describe the solution you'd like**
Create a Docusaurus setup for Reassure! Regarding content we should start with having a single "Getting Started" page that will contain Readme.md file. We also need to have a typical sidebare where we would be able to add more docs pages in the future.

This documentation will be published using GH pages.

**Comment by dmahajan980** [comment]
Hi @mdjastrzebski, I'd like to pick this up!

**Comment by mdjastrzebski** [comment]
@dmahajan980 I've got another contributor started working on this already. Hacktoberfest is hotter season that I expected. Maybe you would like to take any of the other hacktoberfest tasks?

**Comment by Xiltyn** [comment]
I just happened to start working on it a bit earlier, thanks for understanding! :)

**Comment by thymikee** [comment]
Closed via #230
