### ISSUE TITLE
Add examples section to the website sidebar

### ISSUE THREAD

**Issue by thymikee** [callstack/reassure#238]
**Describe the improvement**

<img width="314" alt="image" src="https://user-images.githubusercontent.com/5106466/197522870-254fbe2b-32bb-4c27-a044-499b76b8a574.png">

This section is missing "Examples". I would expect it to be a simple list to our existing examples on GitHub: https://github.com/callstack/reassure/tree/main/examples

**Comment by octosapien** [comment]
I would love to work on this . 
Please assign me this issue .

**Comment by yashjoshi-dotcom** [comment]
Hi, Would love to work on this issue but am finding it the repo a little overwhelming. Can you point me towards the section of the repo where I could find the files for the website ? 
I am a bit new to working with big codebases hence a little confused, Hope you will understand  <3

**Comment by yashjoshi-dotcom** [comment]
Edit 1: On browsing and using the search feature of vs code :)  I have finally found the files. The thing is I have learnt the basics of ReactJs so know little about the current file structure but I am willing to learn along the way. 
Will require some help from your side initially so should I work on this ?

**Comment by thymikee** [comment]
@yashjoshi-dotcom please ask if you need any assistance :)

**Comment by thymikee** [comment]
Docs files can be found here: https://github.com/callstack/reassure/tree/main/docusaurus
