### ISSUE TITLE
[BUG] Windows support | error SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by edenizk** [callstack/reassure#255]
**Describe the bug**
I am not sure if this issue supposes to be a feature or a bug.
When I am running the reassure on windows (tested on 11 and 10), getting this error: 
![image](https://user-images.githubusercontent.com/35309972/202551352-09b30c9d-79a5-4a0a-89e2-785358a99a54.png)

**To Reproduce**
1. Clone Reassure example in windows
2. Install packages
3. Run `yarn reassure`
4. See the error

**Expected behavior**
For now I am setting the `TEST_RUNNER_PATH` to `node_modules/jest/bin/jest`

**Screenshots**
After setting `TEST_RUNNER_PATH`:
![image](https://user-images.githubusercontent.com/35309972/202552803-4ca95519-ab5f-4fb4-89b2-a7e60de98189.png)

**Desktop (please complete the following information):**
 - Windows 11 | node: v16.13.0

**Additional context**
If anyone else has the same problem my solution was to add the cross-env package and set to package.json script to this
` "perf-test": "cross-env TEST_RUNNER_PATH=node_modules/jest/bin/jest reassure"`

**Comment by thymikee** [comment]
We'd happily accept the PR fixing this for Windows users :) Or at least documenting the usage of `cross-env`.

**Comment by davincho** [comment]
I had the same issue on a Apple M1 Pro / 13.0 - setting the `TEST_RUNNER_PATH` explicitly (as described above) fixed my problem.

**Comment by edenizk** [comment]
> I had the same issue on a Apple M1 Pro / 13.0 - setting the `TEST_RUNNER_PATH` explicitly (as described above) fixed my problem.

Thank you for the information, in this case I might need to update my PR. 
I thought my solution is valid only for the windows, because I took solution from jest documentation here:

https://jestjs.io/docs/troubleshooting#debugging-in-vs-code
