### ISSUE TITLE
[FEATURE] Ability to run reassure for a single file

### ISSUE THREAD

**Issue by katanasushi** [callstack/reassure#314]
**Is your feature request related to a problem? Please describe.**
Is it possible to run reassure for a single file? I have a lot of perf-test.js files in my project and sometimes when I change one file it does not get automatically picked to be the 1st one

**Describe the solution you'd like**
Being able to run tests for a single file like `npx reassure ./tests/example.perf-test.js`

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by thymikee** [comment]
You should be able to accomplish this today with `TEST_RUNNER_ARGS` (which defaults to `--runInBand --testMatch "<rootDir>/**/*.perf-test.[jt]s?(x)"'`):

```sh
TEST_RUNNER_ARGS="--runInBand ./tests/example.perf-test.js" npx reassure
```

**Comment by zacharyfmarion** [comment]
@thymikee it's possible, but not very ergonomic for development. Would be nice for the binary to have a format more like jest does, allowing for testing matching like they describe

**Comment by thymikee** [comment]
I agree. Would you like to explore ergonomic yet future-proof interface for such an option?

**Comment by Xiltyn** [comment]
@thymikee I'm down to check this one out and try to work out a solution as it doesn't seem to have been picked up yet.

Cheers.

**Comment by Xiltyn** [comment]
Posted a PR with a potential solution, we may discuss whether this is viable or not further ;) Feel free to take a look
