### ISSUE TITLE
[BUG]: measure code is running under incorrect Node.js configuration.

### ISSUE THREAD

**Issue by seyaobey-dev** [callstack/reassure#368]
**Describe the bug**
running command `yarn reassure` fails with error though the test completes successfully 
```
Reassure: measure code is running under incorrect Node.js configuration.
    Performance test code should be run in Jest with certain Node.js flags to increase measurements stability.
    Make sure you use the Reassure CLI and run it using "reassure" command.
```
I have created a fresh `Expo SDK 48` project and added `reassure` by following official tutorial. I have set a simple component:
```
export default function Index() {
    return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <Text>hello world</Text>
        </View>
    )
}
```
Then I setup a simple performance measurement test:
```
import { measurePerformance } from 'reassure';
import Component from '__path_to_component';

test('auth performance', async () => {
    await measurePerformance(<Component />);
});
```

Running `yarn reassure` throw above error:
![image](https://user-images.githubusercontent.com/83374925/221420344-52638b7a-bb85-4832-95e9-182c112b5170.png)

**To Reproduce**
1. Create new Expo SDK 48 project
2. Add `jest, jest-expo, @testing-library/react-native` and configure accordingly
3. Run a simple performance test and `yarn reassure`
4. Observe above warning/error

**Expected behavior**
Execution should complete without warning or error

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 
 **Additional context**
```
"reassure": "^0.7.1"
"expo": 48.0.1,
"react-native": "0.71.3",   
"jest": "^29.2.1",
"jest-expo": "^48.0.1",
"@testing-library/jest-native": "^5.4.2",
```

`jest.config.json`
```
module.exports = {
    preset: "jest-expo",
    setupFilesAfterEnv: ["<rootDir>/jest.setup.tsx"],
    transformIgnorePatterns: [
        "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
}
```

**Comment by mdjastrzebski** [comment]
@seyaobey-dev Reassure 0.9.0, released yesterday should fix this issue, as it contains support for using `jest-expo`.
