### ISSUE TITLE
React (web) support

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#39]
Scope:
* separate import for using RTL and React.js
* duplicate `renderMeasure` using RTL `render` and `RenderAPI`
* web example app (tests actually)

**Comment by ShaswatPrabhat** [comment]
Hey @mdjastrzebski  can you please share more context on this, wanted to take a shot at this as well .

Thanks in advance.

**Comment by thymikee** [comment]
I consider it done.
