### ISSUE TITLE
Query : Not able to render the page for reassure test with MockedProvider

### ISSUE THREAD

**Issue by g-tiwari** [callstack/reassure#405]
**Describe the Query**
I am writing some asynchronous test using reassure. I am using Apollo mockProvider to mock graphql data. My react native integration tests works fine. But Reassure MeasureRenderer is not rendering the data coming from mock response. I have used custom wrapper option from MeasureOptions interface. but it does not seem to work

Can someone post some examples of reassure tests with MockedProvider wrapper ?

**Comment by mdjastrzebski** [comment]
@g-tiwari could you provide a minimal reproduction repository based on one of our [example apps](https://github.com/callstack/reassure-examples/), so that we can investigate the case?

**Comment by mdjastrzebski** [comment]
Closing as stale and non-actionable.
