### ISSUE TITLE
[BUG] Installing Reassure fails other React native integration tests which uses MockProvider

### ISSUE THREAD

**Issue by g-tiwari** [callstack/reassure#407]
**Describe the bug**
Installing Reassure fails other React native integration tests which uses MockProvider

**To Reproduce**
1. Pick a fresh project which has RNTL integration tests which uses MockedProvider to mock graphql response
2. Install reassure
3. Now execute your usual integration test with jest
4. All steps where any mock response was expected from graphql, start failing

**Expected behavior**
Existing jest test should not fail, reassure should be able to handle graphql MockedProvider wrapper and its response

**Screenshots**

**Additional context**
Also any reassure test which require MockedProvider also does not work

**Comment by mdjastrzebski** [comment]
@g-tiwari could you provide a minimal reproduction repo that showcases the issue? Optimally it should be based on ones  Reassure [example apps](https://github.com/callstack/reassure-examples).

**Comment by g-tiwari** [comment]
Sure, Are there examples apps based on Apollo GraphQL ? I can not see one.

**Comment by mdjastrzebski** [comment]
@g-tiwari take one of the example apps (e.g. `native`) and add GraphQL deps + minimal code so that we can reproduce the error without the burden of having to dig through larger code base.

**Comment by mdjastrzebski** [comment]
Closing as stale and non-actionable.
