### ISSUE TITLE
Discussion: Reassure v1.0

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#414]
Reassure seems to have reached level when it can be considered feature complete for it's basic role of measuring React Native / React render performance using RNTL / RTL. The basic workflow for baseline vs current testing proven to be reasonable. The file formats (.perf, output.json) seem to be adequate, esp. including `metadata` part.

Therefore, I wanted to start a short discussion whether we are ready for v1 or is there something still missing that should be considered essential.

From my perspective:
1. The recent addition of `measureFunction` API has left `measurePerformance` somewhat inadequately named. Therefore, I think we should rename it to `measureRender`. We can keep `measurePerformance` with deprecation warning to ease user migration.
2. The improvements suggested in our issues are nice additions but they do not seem to constitute core features for this tool.

CC: @thymikee @Xiltyn @adhorodyski @jbinda @gedu

**Comment by g-tiwari** [comment]
If we can find a way to reuse existing integration tests and use them as perf tests, that would be great.
Not sure if someone solved it or have a workaround.
I have more than 1000 tests and want to reuse 50-100 tests as perf test out of those. If we can have a way to automatically convert them in to perf test

**Comment by gedu** [comment]
Yes, from my side makes sense the rename update and move to 1.0

**Comment by thymikee** [comment]
I’m good with cutting the stable version at this point. It’s fine to keep `measurePerformance` as an alias for backwards compatibility, no need to deprecate it just yet as it will likely slow down the upgrade.

Once v1 is cut, we can think about next steps for this library and what we want to prioritize.

**Comment by mdjastrzebski** [comment]
[Reassure v1](https://github.com/callstack/reassure/releases/tag/reassure%401.0.0) has been released! 🎉
