### ISSUE TITLE
[FEATURE] Support for NextJS setups not using Babel.

### ISSUE THREAD

**Issue by MeanBoyCousin** [callstack/reassure#425]
**Is your feature request related to a problem? Please describe.**
I'm attempting to set up Reassure for a NextJS 14 application (using the new app router, SWC, etc.) and running Reassure is complaining about Babel config which the project doesn't have.

**Describe the solution you'd like**
A way to implement reassure without the need for Babel.

**Describe alternatives you've considered**
N/A

**Additional context**
Here's a small snippet from the output (happy to share more detail if needed).

```bash
 ● Test suite failed to run

Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
```

**Comment by mdjastrzebski** [comment]
Are you user this is Reassure issue? Reassure itself does not have a direct dependency or use of Babel. Most probably this is a Jest issue.

**Comment by mdjastrzebski** [comment]
Vite yes (with Babel - see [example repo](https://github.com/callstack/reassure-examples/tree/main/examples/web-vite)), Vitest probably no. Contribution in this area are welcomed.
