### ISSUE TITLE
[BUG] Module '"reassure"' has no exported member 'measureRenders'

### ISSUE THREAD

**Issue by sbalay** [callstack/reassure#447]
**Describe the bug**
Following the README instructions I wrote my test case:

```
import { measureRenders } from 'reassure';
import { screen, fireEvent } from '@testing-library/react-native';
import { ComponentUnderTest } from './ComponentUnderTest';

test('Test with scenario', async () => {
  const scenario = async () => {
    fireEvent.press(screen.getByText('Go'));
    await screen.findByText('Done');
  };

  await measureRenders(<ComponentUnderTest />, { scenario });
});
```

However, as my test file is written in typescript, I got the following error on vscode: `Module '"reassure"' has no exported member 'measureRenders'.ts(2305)`

It might be that I made a mistake following the instructions, or either the typescript types of the library are wrong or the README is outdated?

**To Reproduce**
Create a stub component in a file called `ComponentUnderTest` and then create a perf-test for it using typescript

```
import { measureRenders } from 'reassure';
import { screen, fireEvent } from '@testing-library/react-native';
import { ComponentUnderTest } from './ComponentUnderTest';

test('Test with scenario', async () => {
  const scenario = async () => {
    fireEvent.press(screen.getByText('Go'));
    await screen.findByText('Done');
  };

  await measureRenders(<ComponentUnderTest />, { scenario });
});
```

See that there's a typescript error reported in vscode

**Expected behavior**
It works

**Screenshots**
I don't think a screenshot would help here

**Additional context**
Using v0.10.2

**Comment by sbalay** [comment]
Just saw that there was a recent rename introduced in https://github.com/callstack/reassure/pull/433

I guess those changes have not been released yet?

Closing, feel free to reopen if needed

**Comment by mdjastrzebski** [comment]
You are right, `measureRenders` is v1.0.0 name for `measurePerformance`. There is 1.0.0-beta, but not stable yet

**Comment by gutenye** [comment]
Had to go here to understand it. Maybe revert the doc changes before the new version is published?

**Comment by mdjastrzebski** [comment]
Published docs fixed.
