### ISSUE TITLE
[FEATURE] Improve `scenario` type def and export `MeasureOptions` from `reassure`

### ISSUE THREAD

**Issue by sbalay** [callstack/reassure#448]
**Is your feature request related to a problem? Please describe.**
Not really a problem but when declaring a scenario and using `screen` as the scenario param instead of importing it from `testing-library`, I would like to have proper types for it.

I tried:

```tsx
import { measurePerformance, MeasureOptions } from 'reassure';
import { fireEvent } from '@testing-library/react-native';
import { ComponentUnderTest } from './ComponentUnderTest';

test('Test with scenario', async () => {
  const scenario: MeasureOptions['scenario'] = async (screen) => {
    fireEvent.press(screen.getByText('Go'));
    await screen.findByText('Done');
  };

  await measureRenders(<ComponentUnderTest />, { scenario });
});
```

But `MeasureOptions` is not available for me to import, and even if it was, I saw the types for scenario just use `any` for the `screen`:

```ts
export interface MeasureOptions {
  runs?: number;
  warmupRuns?: number;
  wrapper?: React.ComponentType<{ children: React.ReactElement }>;
  scenario?: (screen: any) => Promise<any>;
}
```

**Describe the solution you'd like**
I can import `MeasureOptions` and `scenario` has proper types for the screen param

**Describe alternatives you've considered**
none

**Additional context**
I guess this is not a huge problem since it only affects codebases relying on old versions of testing-library where you can not import `screen` from there... still... seems like a quick fix and a nice improvement for `reassure`

Using v0.10.2

**Comment by sbalay** [comment]
Seems that the export has already been tackled [here](https://github.com/callstack/reassure/pull/433) but they type still relies on `any`

**Comment by mdjastrzebski** [comment]
You could explicitly type `screen` as `RenderResult` from RNTL. The reason why Reassure uses `any` is that you can also use it with React Testing Library, which has a different type.

**Comment by mdjastrzebski** [comment]
Closing as solved by workaround.
