### ISSUE TITLE
[Improvement] The suggested CI script should only reinstall dependencies if they changed between baseline branch and target branch

### ISSUE THREAD

**Issue by sbalay** [callstack/reassure#449]
**Describe the improvement**
The current docs suggested the following script to run this tool on CI:

```
#!/usr/bin/env bash
set -e

BASELINE_BRANCH=${BASELINE_BRANCH:="main"}

# Required for `git switch` on CI
git fetch origin

# Gather baseline perf measurements
git switch "$BASELINE_BRANCH"
yarn install --force
yarn reassure --baseline

# Gather current perf measurements & compare results
git switch --detach -
yarn install --force
yarn reassure
```

It would be nice to only run the second `yarn install --force` if the lockfile of the target branch is different from the baseline branch.

**Scope of improvement**
The CI script

**Suggested implementation steps**
Maybe hash the lockfile while on the baseline branch and then rehash it after switching to the target branch. Finally compare both hashes and run `yarn install --force` on the target branch based on the comparison result

**Comment by mdjastrzebski** [comment]
Closing as our default template no longer uses `--force` option for `yarn install` in `reassure-tests.sh`:
https://github.com/callstack/reassure/blob/main/packages/cli/src/templates/reassure-tests
