### ISSUE TITLE
[Improvement] replace the unmaintained markdown-builder package

### ISSUE THREAD

**Issue by meteorlxy** [callstack/reassure#451]
**Describe the improvement**

The [markdown-builder](https://github.com/Chalarangelo/markdown-builder) package is no longer maintained since 2019.

It introduces a redundant legacy version of husky in its dependencies, which pollutes the dependency tree:

https://github.com/callstack/reassure/blob/04825689671482beca6f90010436c44c878076e3/yarn.lock#L6318-L6323

Although it could be resolved by the "resolutions" feature of some package manager, I think it could be better to replace it totally from the `@callstack/reassure-compare` package.

I found there is a fork [mr_markdown_builder](https://www.npmjs.com/package/mr_markdown_builder) and maybe we can make use of it directly?

**Comment by mdjastrzebski** [comment]
I've did a quick check where do we use markdown builder and it's pretty minimal. We just use `headers.h1`, `headers.h3` `emphasis.b` and `emphasis.i`. Replacements for this should be easy to add to `reassure-compare` directly. @meteorlxy would you like to contribute it?
