### ISSUE TITLE
[FEATURE] Run single Reassure test

### ISSUE THREAD

**Issue by yakupdurmus** [callstack/reassure#498]
Isn't there a way to run a single test?

When I look at the options, it doesn't seem to support it.

I want to run a single test.

For example

`yarn reassure ./__tests__/screens/Homepage.perf-test.tsx'`

It is also possible to run Jest test like this:

`npx jest './__tests__/screens/HomePage.test.tsx' -t`

**Comment by mdjastrzebski** [comment]
@yakupdurmus Interesting idea. We currently support [`--testMatch` option](https://callstack.github.io/reassure/docs/installation#writing-your-first-test), modelled after Jest. You can use it to match a single file or a glob. 

Does that match your use-case, or is the some benefit of just providing file path? Would you be open to submitting a PR for that?

**Comment by yakupdurmus** [comment]
Thanks for your answer **--testMatch** worked for me.


`yarn reassure --testMatch __tests__/HomePage.perf-test.tsx`
