### ISSUE TITLE
Add a flag to allow testRegex pattern in jest config

### ISSUE THREAD

**Issue by Saurabh1708** [callstack/reassure#508]
**Is your feature request related to a problem? Please describe.**
My org uses **testRegex** in the jest.config instead of testMatch and since both cannot exist simultaneously, we have to modify the config before running the reassure tests. 

**Describe the solution you'd like**
I would want to be able to add a **--testRegex** flag to the reassure measure command to be able to use testRegex instead of testMatch

**Describe alternatives you've considered**
I'm open to suggestions for a better solution.

**Comment by mdjastrzebski** [comment]
I am considering adding a feature where `reassure` would foward all passed options to underlying `jest` bin. It seams that would solve your issue

**Comment by Saurabh-Dream11** [comment]
Thanks for the update. Will try implementing `TEST_RUNNER_ARGS`.

**Comment by mdjastrzebski** [comment]
This issue has been resolved in Reassure [v1.2.0](https://github.com/callstack/reassure/releases/tag/reassure%401.2.0) 🎉
