### ISSUE TITLE
[FEATURE] Coverage = false and Watch

### ISSUE THREAD

**Issue by marcozciuffini** [callstack/reassure#510]
**Is your feature request related to a problem? Please describe.**
When testing one component whilst devving, I find the coverage in the project to get in the way
I also would like it to auto run on save of the file, similar to how we can in jest. 

that way I could run `yarn reassure --testMatch=${path-to-file} --watch --coverage=false` just to

**Describe the solution you'd like**
an option of --coverage=false or --collectCoverageFrom=${path-to-file} to help me to view the issues without scrolling past coverage and an option of watch to autoRun the command on save of the file/files

**Comment by mdjastrzebski** [comment]
Are ` --coverage=false`/`--collectCoverageFrom` Jest flags? I am considering adding a feature where `reassure` would foward all passed options to underlying `jest` bin. I wonder if that would solve your issue.

**Comment by marcozciuffini** [comment]
Sounds like it would perfectly 👍🏼 thanks for the quick response

**Comment by mdjastrzebski** [comment]
This issue has been resolved in Reassure [v1.2.0](https://github.com/callstack/reassure/releases/tag/reassure%401.2.0) 🎉
