### ISSUE TITLE
monorepo: cleanup deps

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#54]
## Description
Since migration to monorepo setup, there are some unnecessary deps packages extracted from single large package.

## Scope
* review `deps`, `devDeps` & `peerDeps` in all packages, remove unnecessary ones

**Comment by ShaswatPrabhat** [comment]
Please find the [PR](https://github.com/callstack/reassure/pull/203)

**Comment by ShaswatPrabhat** [comment]
Hi @mdjastrzebski  the above PR has been merged, can we please close this issue ?
