### ISSUE TITLE
refactor: extract `reassure-danger` package

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/reassure#59]
**Describe the improvement**
Currently the Danger JS pluging code is in main `reassure` package. As we now have monorepo and plan to have multiple CI integrations it should be moved to its own `reassure-danger` package.

**Scope of improvement**
* extract Danger JS plugin from `reassure` package to `reassure-danger`

**Suggested implementation steps**
1. Extract plugin

**Comment by ShaswatPrabhat** [comment]
Hi, I will like to contribute for the above change please.
Please let me know if I can raise a PR for the same

**Comment by thymikee** [comment]
@ShaswatPrabhat please do! 🙂

**Comment by ShaswatPrabhat** [comment]
Please find the [PR](https://github.com/callstack/reassure/pull/118)

Please guide if there are be any changes I have missed.

Thanks in advance!

**Comment by mdjastrzebski** [comment]
Resolved in #118
