### ISSUE TITLE
Question - Reassure + Expo

### ISSUE THREAD

**Issue by nicoache1** [callstack/reassure#69]
## Description

Im trying to use Reassure with Expo and it display some errors as you see below.

![Captura de Pantalla 2022-07-01 a la(s) 14 21 51](https://user-images.githubusercontent.com/26419582/176941662-8cb75db2-2c64-48c6-bdc5-db32f0378d27.png)

Anyone have any idea if Reassure should work with Expo or the error its related with something different?

## Environment
```
"expo": "~45.0.0",
"react-native": "0.68.2",
"react": "17.0.2",
"jest": "^26.6.3",
"jest-expo": "^45.0.1",
"@testing-library/jest-native": "^4.0.5",
"@testing-library/react-native": "^10.1.1",
"react-test-renderer": "^17.0.2",
"reassure": "^0.1.0",
```

**Comment by thymikee** [comment]
Can you share how are you running your tests? I'm interested in commands used. This error triggers if Node failed to set an `--expose-gc` flag and thus making `global.gc` undefined. We set this flag automatically when running `npx reassure meassure`

**Comment by Brad19** [comment]
@thymikee 
Im also getting the same error. Here is the package.json
`console.error
    ❌ Reassure: measure code is running under incorrect Node.js configuration.
    Performance test code should be run in Jest with certain Node.js flags to increase measurements stability.
    Make sure you use the public API and run it using "reassure-tests" command.

      67 |   }
      68 | 
    > 69 |   originalConsoleError(message);
         |   ^
      70 | };
      71 | 
      72 | afterEach(() => {

      at console.error (scripts/setup-tests.js:69:3)
      at showFlagsOuputIfNeeded (node_modules/@reassure/reassure-measure/lib/commonjs/output.ts:36:13)
      at measureRender (node_modules/@reassure/reassure-measure/lib/commonjs/measure.tsx:36:3)
      at Object.reassure_1 (node_modules/@reassure/reassure-measure/lib/commonjs/measure.tsx:19:23)
      at _callee$ (src/components/toast/Toast.test.tsx:6:24)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)`

And.  I ran the command from one our scripts mentioned below

npm run test:watch:single "path to the  sample.test.tsx"

Here is our config 
node - 14.19

package.json

```{
scripts: {
 "test": "jest --coverage --env=node --forceExit src __tests__", 
 "test:watch:single": "jest --watch --env=node --forceExit", 
}
"dependencies": {
 "react-native": "0.67.3",
 }
 "devDependencies": {
    "jest": "^26.6.3",
  }
}
```
Please advise

Thanks,
Brad

**Comment by thymikee** [comment]
Hey @Brad19 
You mean these scripts?
```
scripts: {
 "test": "jest --coverage --env=node --forceExit src __tests__", 
 "test:watch:single": "jest --watch --env=node --forceExit", 
}
```
These are for running your regular tests. Performance tests are ran differently. Please follow the setup instructions specified here: https://github.com/callstack/reassure#write-performance-testing-script

**Comment by mdjastrzebski** [comment]
@nicoache1 please check #75 for a correct Expo-based project setup. Generally it is the same as for React Native CLI project.

**Comment by sregg** [comment]
I'm also getting the same error message when running `yarn reassure` on a RN CLI project.
```
  console.error
    ❌ Reassure: measure code is running under incorrect Node.js configuration.
    Performance test code should be run in Jest with certain Node.js flags to increase measurements stability.
    Make sure you use the Reassure CLI and run it using "reassure" command.
```

reassure: v0.4.1
node: v14.17.6
yarn: v1.22.19

Here's our test file:

```
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { measurePerformance } from 'reassure';
import { SearchFiltersScreen } from '../../app/screens';
import { server } from '../mock-server/setupMockServer';
import { createLoggedInWrapper } from '../wrapper-providers';

const LoggedInWrapper = createLoggedInWrapper();
const Stack = createNativeStackNavigator();

const ComponentWithWrappers = () => (
  <LoggedInWrapper>
    <NavigationContainer>
      <Stack.Screen name="searchFilters" component={SearchFiltersScreen} />
    </NavigationContainer>
  </LoggedInWrapper>
);

describe('Search Filters Screen Performance', () => {
  beforeAll(() => server.listen());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());

  test('Initial load', async () => {
    await measurePerformance(<ComponentWithWrappers />);
  });
});

```
