### ISSUE TITLE
Introduce a logger so we can opt-out from logging some messages

### ISSUE THREAD

**Issue by thymikee** [callstack/reassure#85]
Ideally something simple, like we have it in RN CLI for example.

_Originally posted by @thymikee in https://github.com/callstack/reassure/pull/76#discussion_r919803111_

**Comment by ShaswatPrabhat** [comment]
Hi, can you please provider a bit more detail on this @thymikee ?

Wanted to understand before taking a shot at this.

**Comment by ShaswatPrabhat** [comment]
Hey @thymikee  can you please share an idea on what kind of logger implementation are you looking for ?

**Comment by mdjastrzebski** [comment]
@ShaswatPrabhat I think @thymikee is thinking about this: https://github.com/react-native-community/cli/blob/main/packages/cli-tools/src/logger.ts

**Comment by mdjastrzebski** [comment]
@ShaswatPrabhat Sure the, pls do!

Just ge aware that I might not be able to review the PR promptly dur to busy time at work.

**Comment by Xiltyn** [comment]
Since no progress has been made here and no PRs introduced, the logger will be supported with PR https://github.com/callstack/reassure/pull/275

**Comment by mdjastrzebski** [comment]
@Xiltyn would it be possible to extract logger from #275 and have it as a smaller PR. It would be much easier to me to diggest.

**Comment by Xiltyn** [comment]
It would but it's a significant time investment and it will take me some time before I can work on it again unfortunately. If we cannot make it work before that time, I'll do that.
